"""empty message

Revision ID: 13afc07c1dfd
Revises: 52710ccd948f
Create Date: 2024-08-26 19:49:39.184451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13afc07c1dfd'
down_revision = '52710ccd948f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
