"""empty message

Revision ID: 47d34aa00bd4
Revises: 1d0afaf47f0d
Create Date: 2024-08-18 18:42:23.123108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d34aa00bd4'
down_revision = '1d0afaf47f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed_by', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('viewed_by')

    # ### end Alembic commands ###
