"""empty message

Revision ID: 6df1d5c44124
Revises: af52f410dba9
Create Date: 2024-08-30 15:23:44.460946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df1d5c44124'
down_revision = 'af52f410dba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed_by', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_message', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('viewed_by')

    # ### end Alembic commands ###
