"""empty message

Revision ID: 86fd0c0da58d
Revises: 48b137a4fcbd
Create Date: 2024-08-28 13:35:51.127158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fd0c0da58d'
down_revision = '48b137a4fcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ferramentas', schema=None) as batch_op:
        batch_op.drop_column('codigo_ferramenta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ferramentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_ferramenta', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
